"""Generate a tiny synthetic Excel file with the same schema as the real data.

Used by CI and the ``make smoke`` target so the pipeline can be exercised
end-to-end without the real observational file. NOT suitable for inference.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

COLUMNS = [
    "STATION ID",
    "LOCATION",
    "DATE TIME",
    "PM10 1H (ug/m3)",
    "PM2.5 1H (ug/m3)",
    "SO2 1H (ppm)",
    "NO2 1H (ppm)",
    "O3 1H (ppm)",
    "CO 1H (ppm)",
    "WIND DIRECTION 1H (deg)",
    "WIND SPEED 1H (m/s)",
    "RELATIVE HUMIDITY 1H (%)",
    "Ambient Temperature 1H (c)",
]


def _fake_year(year: int, include_o3: bool = True) -> pd.DataFrame:
    start = pd.Timestamp(year, 1, 1)
    end = pd.Timestamp(year, 12, 31, 23)
    ts = pd.date_range(start, end, freq="H")
    rng = np.random.default_rng(year)
    hour = ts.hour
    doy = ts.dayofyear

    seasonal = 5 * np.sin(2 * np.pi * doy / 366)
    diurnal = 3 * np.sin(2 * np.pi * hour / 24 + np.pi / 3)
    noise = rng.normal(0, 2.5, size=ts.size)
    pm25 = np.clip(15 + seasonal + diurnal + noise, 1, None)
    pm10 = np.clip(pm25 * 1.4 + rng.normal(0, 2, ts.size), 1, None)
    so2 = np.clip(0.004 + 0.001 * rng.standard_normal(ts.size), 0, 0.05)
    no2 = np.clip(0.02 + 0.005 * rng.standard_normal(ts.size), 0, 0.2)
    o3 = np.clip(
        0.02 + 0.01 * np.sin(2 * np.pi * hour / 24) + 0.004 * rng.standard_normal(ts.size), 0, 0.2
    )
    co = np.clip(0.9 + 0.2 * rng.standard_normal(ts.size), 0, 5)
    wdir = (rng.uniform(0, 360, size=ts.size)) % 360
    wspd = np.clip(1.5 + 0.6 * rng.standard_normal(ts.size), 0, 10)
    rh = np.clip(75 + 10 * np.sin(2 * np.pi * hour / 24) + rng.normal(0, 4, ts.size), 20, 100)
    temp = np.clip(27 + 3 * np.sin(2 * np.pi * hour / 24) + rng.normal(0, 1.2, ts.size), 15, 40)

    df = pd.DataFrame(
        {
            "STATION ID": "CA06P",
            "LOCATION": "Seberang Jaya, PULAU PINANG",
            "DATE TIME": ts,
            "PM10 1H (ug/m3)": pm10.round(3),
            "PM2.5 1H (ug/m3)": pm25.round(3),
            "SO2 1H (ppm)": so2.round(4),
            "NO2 1H (ppm)": no2.round(4),
            "O3 1H (ppm)": o3.round(4) if include_o3 else np.nan,
            "CO 1H (ppm)": co.round(3),
            "WIND DIRECTION 1H (deg)": wdir.round(3),
            "WIND SPEED 1H (m/s)": wspd.round(3),
            "RELATIVE HUMIDITY 1H (%)": rh.round(3),
            "Ambient Temperature 1H (c)": temp.round(3),
        }
    )
    if not include_o3:
        df = df.drop(columns=["O3 1H (ppm)"])
    return df[[c for c in COLUMNS if c in df.columns]]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="data/sample")
    parser.add_argument("--years", nargs="+", type=int, default=[2018, 2019, 2020, 2021])
    args = parser.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    xlsx_path = out_dir / "synthetic_seberang_jaya.xlsx"
    with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
        for y in args.years:
            df = _fake_year(y, include_o3=(y != 2021))
            df.to_excel(writer, sheet_name=str(y), index=False)
    (out_dir / "README.md").write_text(
        "# Synthetic sample\n\n"
        "This folder contains a deterministic, synthetic replica of the Seberang Jaya 2018-2021 "
        "air-quality Excel workbook, generated by `scripts/generate_synthetic_sample.py`. It is "
        "intended **only** for smoke-testing the pipeline and CI, and must not be used for "
        "scientific inference.\n",
        encoding="utf-8",
    )
    print(f"Wrote {xlsx_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
